### ISSUE TITLE
How to create using `polymer init`

### ISSUE THREAD

**Issue by ztzven** [LostInBrittany/uniflow-polymer-starter-kit#1]
Looks like you're using the `polymer-starter-kit` documentation..
How would I init a new project using this kit? i.e. is this repo a generator? Or should I copy straight from source?

**Comment by LostInBrittany** [comment]
Hi!

Yes, there was something missing, the  generator allowing to use this starter kit as a template in Polymer CLI. 

I prepared it yesterday, it's in a sister repository, https://github.com/LostInBrittany/generator-polymer-init-uniflow-polymer-starter-kit.

So now, in order to use `uniflow-polymer-starter-kit` in Polymer CLI you can simply do:

1. install  `generator-polymer-init-uniflow-polymer-starter-kit` using npm:
  
      npm install -g generator-polymer-init-uniflow-polymer-starter-kit

1. initialize project from template

  Generate your new project using polymer init:

      mkdir my-app
      cd my-app
      polymer init uniflow-polymer-starter-kit
